language: c
os:
  - linux
  - osx
sudo: required
services:
  - docker
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then docker build -t learn-ocaml --target program .; fi
script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -c 'docker run --rm -v $(pwd)/demo-repository:/repository learn-ocaml -- build'; fi
