# Note: remove this file (squash-removing the underlying commit) before merging
name: Push oauth-moodle to DockerHub
on:
  push:
    branches:
      - oauth-moodle
      - oauth-moodle-dev
jobs:
  push_server:
    name: Push learn-ocaml image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get branch name
        run: branch="${{ github.ref }}"; echo "::set-output name=branch::${branch#refs/heads/}"
        id: branch
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          always_pull: true
          add_git_labels: true
          labels: "org.opencontainers.image.version=${{ steps.branch.outputs.branch }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # repository: ocamlsf/learn-ocaml
          repository: pfitaxel/learn-ocaml
          tags: ${{ steps.branch.outputs.branch }}
  push_client:
    name: Push learn-ocaml-client image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get branch name
        run: branch="${{ github.ref }}"; echo "::set-output name=branch::${branch#refs/heads/}"
        id: branch
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          always_pull: true
          add_git_labels: true
          labels: "org.opencontainers.image.version=${{ steps.branch.outputs.branch }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # repository: ocamlsf/learn-ocaml-client
          repository: pfitaxel/learn-ocaml-client
          target: client
          tags: ${{ steps.branch.outputs.branch }}
  push_emacs_client:
    name: Push emacs-learn-ocaml-client image to Docker Hub
    needs: push_client
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Get branch name
        run: branch="${{ github.ref }}"; echo "::set-output name=branch::${branch#refs/heads/}"
        id: branch
      - name: Push to Docker Hub
        # https://github.com/docker/build-push-action/tree/releases/v1#readme
        uses: docker/build-push-action@v1
        with:
          path: ci/docker-emacs-learn-ocaml-client
          build_args: "base=pfitaxel/learn-ocaml-client,version=${{ steps.branch.outputs.branch }}"
          always_pull: true
          add_git_labels: true
          labels: "org.opencontainers.image.version=${{ steps.branch.outputs.branch }}"
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # repository: ocamlsf/learn-ocaml
          repository: pfitaxel/emacs-learn-ocaml-client
          tags: ${{ steps.branch.outputs.branch }}
